---
title: "stl_lead_inequity"
author: "Heather"
format: html
editor: visual

execute: 
  warning: false
---

```{r}
library(tidyverse)
library(janitor)
library(here)
library(dplyr)  

```

```{r}
stl_lead <- read_csv(here::here("data","stl_lead.csv")) %>% 
  janitor::clean_names()
view(stl_lead)
summary(stl_lead)
```

```{r}
stl_lead_prop <- data.frame(stl_lead)
lead_data <- dplyr::mutate(stl_lead, prop_white = white / total_pop)

```

```{r}
stl_lead_plot <- ggplot(lead_data, aes(x = prop_white, y = pct_elevated))+
  geom_point(
    aes(color = count_tested/total_pop,
        size = poverty_tot_moe/poverty_tot)
  )
stl_lead_plot
ggsave(here::here("figs", "stl_lead_plot.png"), height = 5, width = 6)

```

This graph shows a correlation between the proportion of white identifying individuals in the census compared to the percentage of individuals with an elevated lead blood level. The data shows that the percentage of individuals with elevated blood levels increases as the proportion of white identifying individuals decreases.

```{r}
ggplot(lead_data, aes(x = pct_elevated))+
  geom_histogram(color = "blue", fill = "grey")+
  theme_light()
```

```{r}
ggsave(here::here("figs", "stl_lead_hist.jpg"), height = 5, width = 6)
```
